import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavbarComponent from "@/components/navbar/NavbarComponent";
import Error from "./error";
import "@/app/global.css"
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import { Suspense } from "react";
import Loading from "./loading";
import {localCustomFont} from "./fonts";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${localCustomFont.variable}`}
>

      {/* here is the place that we render navbar component in every page in the user layout */}
      <header>
        <NavbarComponent/>
      </header>

      {/* here is the place that each page of child will be render (children) */}
      <ErrorBoundary errorComponent={Error}>
					<Suspense fallback={<Loading />}>{children}</Suspense>
				</ErrorBoundary>
      </body>
    </html>
  );
}
